spring:
  application:
    name: weshopify-authn-service
  redis:
    host: ${AUTHN_REDIS_SERVER_HOST:localhost}
    port: ${AUTHN_REDIS_SERVER_PORT:6379}
    password: ${AUTHN_REDIS_SERVER_PASSWORD:Redis123$}
server:
  port: ${AUTHN_SERVICE_PORT:5022}
weshopify:
   oauth2:
      clientId: ${WSO2_CLIENTID:ofFfsSaLrF4Vec_o4dsAwSWS72ka}
      clientSecret: ${WSO2_CLIENT_SECRET:HEgOiwXoI1XRTp73d_m65S4pliIa}
      userInfo: https://${WSO2_SERVER_HOST:localhost}:${WSO2_SERVER_PORT:9443}/oauth2/userinfo?schems=
      grantType: ${WSO2_GRANT_TYPE:password}
      scope: ${WSO2_OAUTH2_SCOPE:openid}
      uri: https://${WSO2_SERVER_HOST:localhost}:${WSO2_SERVER_PORT:9443}/oauth2/token
      logoutUri: https://${WSO2_SERVER_HOST:localhost}:${WSO2_SERVER_PORT:9443}/oauth2/revoke
